#!/bin/sh
name="syncthing"
uid=$(id -u)
gid=$(id -g)

podman rm -f "${name}" || true

exec podman run --rm --name "${name}" \
    --user "${uid}:${gid}" \
    --userns=keep-id \
    --hostname=$hostname \
    -p 127.0.0.1:8384:8384 \
    -p 22000:22000/tcp \
    -p 22000:22000/udp \
    -p 21027:21027/udp \
    -v syncthing:/var/syncthing \
    -v ${HOME}/Sync:/var/syncthing/Sync \
    docker.io/syncthing/syncthing:latest
